export const wrapper: string;
export const left: string;
export const title: string;
export const logo: string;
export const center: string;
export const right: string;
export const login: string;
export const location: string;
export const edit: string;